name: firestore_example
description: Demonstrates how to use the cloud_firestore_mocks plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  cloud_firestore_mocks:
    path: ../

# Force flutter_driver to use crypto 3 and convert 3.
dependency_overrides:
  crypto: ^3.0.0
  convert: ^3.0.0

flutter:
  uses-material-design: true
