# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  errors:
    # TODO(https://github.com/atn832/cloud_firestore_mocks/issues/157): remove this exception when the null-safe update to flutter_driver is released (Flutter 2.10).
    import_of_legacy_library_into_null_safe: ignore
#   exclude:
#     - path/to/excluded/files/**
